### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by fly800** [gordtulloch/mlCloudDetect#5]
After running for a night, I got the following error:

 

mlCloudDetect by Gord Tulloch gord.tulloch@gmail.com 1.0.0
Usage: mlCloudDetect with no parameters. See mlCloudDetect.ini for input parameters
Traceback (most recent call last):
  File "/home/admin/mlCloudDetect/mlCloudDetect.py", line 68, in <module>
    result,text=clouds.isCloudy()
                ^^^^^^^^^^^^^^^^^
  File "/home/admin/mlCloudDetect/mcpClouds.py", line 69, in isCloudy
    result=self.detect(image_file)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/mlCloudDetect/mcpClouds.py", line 82, in detect
    prediction = self.model.predict(image_array)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/mlCloudDetect/.venv/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/admin/mlCloudDetect/.venv/lib/python3.11/site-packages/keras/src/utils/io_utils.py", line 98, in print_msg
    sys.stdout.write(message)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 18-37: ordinal not in range(256)

 

The UnicodeEncodeError is likely caused by non-ASCII characters being written to a log file or printed to the terminal when the system is trying to encode them using the latin-1 encoding.

**Comment by fly800** [comment]
I did git pull under cd /mlCloudDetect.  I get

Updating adee05d..491f1ba
error: Your local changes to the following files would be overwritten by merge:
        mcpClouds.py
Please commit your changes or stash them before you merge.

I had hard code  "prediction = self.model.predict(image_array,verbose=0)" in my installation.  I changed my location where it's night. Now it works.  I will try at my location tonight.

Thanks very much.
